Traceback (most recent call last):
  File "/home/matthias/workspace/eclipse-sumo/sumo/tests/../tests/complex/traci/ContextSubscriptionFilters/turn/turn_d50_u50_crossing/runner.py", line 84, in <module>
    runSingle(100, float(sys.argv[2]), float(sys.argv[3]))
  File "/home/matthias/workspace/eclipse-sumo/sumo/tests/../tests/complex/traci/ContextSubscriptionFilters/turn/turn_d50_u50_crossing/runner.py", line 47, in runSingle
    responses = traci.simulationStep()
  File "/home/matthias/workspace/eclipse-sumo/sumo/tools/traci/main.py", line 228, in simulationStep
    return _connections[""].simulationStep(step)
  File "/home/matthias/workspace/eclipse-sumo/sumo/tools/traci/connection.py", line 316, in simulationStep
    result = self._sendCmd(tc.CMD_SIMSTEP, None, None, "D", step)
  File "/home/matthias/workspace/eclipse-sumo/sumo/tools/traci/connection.py", line 181, in _sendCmd
    return self._sendExact()
  File "/home/matthias/workspace/eclipse-sumo/sumo/tools/traci/connection.py", line 91, in _sendExact
    raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO
